package cn.adwalker.model.report.domain;

import java.util.Date;

/**
 * TStatReportItem generated by MyEclipse Persistence Tools
 */

public class TStatReportItem implements java.io.Serializable {

    // Fields

    private Long id;
    private Long tableId;
    private String sqlName;
    private String jspName;
    private String format;
    private String status;
    private Integer sequence;
    private String isSearch;
    private String jspType;
    private String sqlType;
    private String originSql;
    private String isLink;
    private String link;
    private Date createtime;
    private String COperator;
    private Date updatetime;
    private String UOpeartor;

    // Constructors

    /** default constructor */
    public TStatReportItem() {
    }

    /** full constructor */
    public TStatReportItem(Long tableId, String sqlName, String jspName,
            String format, String status, Integer sequence, String isSearch,
            String jspType, String sqlType, String originSql, String isLink,
            String link, Date createtime, String COperator, Date updatetime,
            String UOpeartor) {
        this.tableId = tableId;
        this.sqlName = sqlName;
        this.jspName = jspName;
        this.format = format;
        this.status = status;
        this.sequence = sequence;
        this.isSearch = isSearch;
        this.jspType = jspType;
        this.sqlType = sqlType;
        this.originSql = originSql;
        this.isLink = isLink;
        this.link = link;
        this.createtime = createtime;
        this.COperator = COperator;
        this.updatetime = updatetime;
        this.UOpeartor = UOpeartor;
    }

    // Property accessors

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTableId() {
        return this.tableId;
    }

    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    public String getSqlName() {
        return this.sqlName;
    }

    public void setSqlName(String sqlName) {
        this.sqlName = sqlName;
    }

    public String getJspName() {
        return this.jspName;
    }

    public void setJspName(String jspName) {
        this.jspName = jspName;
    }

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getIsSearch() {
        return this.isSearch;
    }

    public void setIsSearch(String isSearch) {
        this.isSearch = isSearch;
    }

    public String getJspType() {
        return this.jspType;
    }

    public void setJspType(String jspType) {
        this.jspType = jspType;
    }

    public String getSqlType() {
        return this.sqlType;
    }

    public void setSqlType(String sqlType) {
        this.sqlType = sqlType;
    }

    public String getOriginSql() {
        return this.originSql;
    }

    public void setOriginSql(String originSql) {
        this.originSql = originSql;
    }

    public String getIsLink() {
        return this.isLink;
    }

    public void setIsLink(String isLink) {
        this.isLink = isLink;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getCOperator() {
        return this.COperator;
    }

    public void setCOperator(String COperator) {
        this.COperator = COperator;
    }

    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getUOpeartor() {
        return this.UOpeartor;
    }

    public void setUOpeartor(String UOpeartor) {
        this.UOpeartor = UOpeartor;
    }

}