package cn.adwalker.model.report.domain;

import java.util.Date;

/**
 * TStatReportTable generated by MyEclipse Persistence Tools
 */

public class TStatReportTable implements java.io.Serializable {
	
    private Long id;
    private String jspName;
    private String menuName;
    private String menuRequest;
    private String originSql;
    private String countSql;
    private Integer pageSize;
    private String status;
    private String role;
    private String note;
    private Date createtime;
    private String COperator;
    private Date updatetime;
    private String UOperator;
    private String totalSql;
    private Integer defaultStart;
    private Integer defaultEnd;
    
    
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getJspName() {
		return jspName;
	}
	public void setJspName(String jspName) {
		this.jspName = jspName;
	}
	public String getMenuName() {
		return menuName;
	}
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}
	public String getOriginSql() {
		return originSql;
	}
	public void setOriginSql(String originSql) {
		this.originSql = originSql;
	}
	public String getCountSql() {
		return countSql;
	}
	public void setCountSql(String countSql) {
		this.countSql = countSql;
	}
	public Integer getPageSize() {
		return pageSize;
	}
	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public Date getCreatetime() {
		return createtime;
	}
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	public String getCOperator() {
		return COperator;
	}
	public void setCOperator(String cOperator) {
		COperator = cOperator;
	}
	public Date getUpdatetime() {
		return updatetime;
	}
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
	public String getUOperator() {
		return UOperator;
	}
	public void setUOperator(String uOperator) {
		UOperator = uOperator;
	}
	public String getTotalSql() {
		return totalSql;
	}
	public void setTotalSql(String totalSql) {
		this.totalSql = totalSql;
	}
	public Integer getDefaultStart() {
		return defaultStart;
	}
	public void setDefaultStart(Integer defaultStart) {
		this.defaultStart = defaultStart;
	}
	public Integer getDefaultEnd() {
		return defaultEnd;
	}
	public void setDefaultEnd(Integer defaultEnd) {
		this.defaultEnd = defaultEnd;
	}
	public String getMenuRequest() {
		return menuRequest;
	}
	public void setMenuRequest(String menuRequest) {
		this.menuRequest = menuRequest;
	}

    
}