create or replace view v_ad_campaign as
select 
	`adv`.`id` AS `adv_id`,
	`adv`.`email` AS `adv_email`,
	`adv`.`company_name` AS `adv_name`,
	`c`.`id` AS `CAMPAIGN_ID`,
	`c`.`campaign_name` AS `CAMPAIGN_NAME`,
	`c`.`price` AS `price`,
	`p`.`name` AS `placement_name`,
	`c`.`charge_type` AS `charge_type`,
	`c`.`salesman_id` AS `salesman_id`,
	`p`.`os` AS `os`,
	`ad`.`ID` AS `ID`,
	`ad`.`PLACEMENT_ID` AS `PLACEMENT_ID`,
	`ad`.`BUDGET_DAY` AS `BUDGET_DAY`,
	`ad`.`BLANCE_PRICE` AS `BLANCE_PRICE`,
	`ad`.`BLANCE_MODE` AS `BLANCE_MODE`,
	`ad`.`TYPE_ID` AS `TYPE_ID`,
	`ad`.`MEDIA_ID` AS `MEDIA_ID`,
	`ad`.`CREATE_TIME` AS `CREATE_TIME`,
	`ad`.`PACKAGE_ID` AS `PACKAGE_ID`,
	`ad`.`STATUS` AS `STATUS`,
	`ad`.`START_TIME` AS `START_TIME`,
	`ad`.`END_TIME` AS `END_TIME`,
	`ad`.`CREATE_USER` AS `CREATE_USER`,
	`ad`.`UPDATE_TIME` AS `UPDATE_TIME`,
	`ad`.`AD_TYPE` AS `AD_TYPE`,
	`ad`.`ONLINE_TIME` AS `ONLINE_TIME`,
	`ad`.`OFFLINE_TIME` AS `OFFLINE_TIME`,
	`ad`.`midia_id` AS `MIDIA_ID`,
	`ad`.`media_name` AS `MEDIA_NAME`,
	`ad`.`COST_DAY` AS `COST_DAY`,
	`ad`.`BUDGET_TYPE` AS `BUDGET_TYPE`,
	greatest(`ad`.`CREATE_TIME`,ifnull(`ad`.`UPDATE_TIME`,'2000-05-07 13:23:44')) AS `release_time` from ((((`v_ad` `ad` left join `t_placement` `p` on((`ad`.`PLACEMENT_ID` = `p`.`id`))) left join `t_campaign_placement_rel` `rel` on((`rel`.`placement_id` = `p`.`id`))) left join `t_campaign` `c` on((`rel`.`campaign_id` = `c`.`id`))) left join `t_advertiser` `adv` on((`c`.`adv_id` = `adv`.`id`)))